greeting:
  message: "hello"

quarkus:
  http:
    cors:
      enabled: true
      origins: http://localhost:4200
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Accept,Authorization,Content-Type,X-Requested-With
  smallrye-openapi:
    path: /openapi
    info-title: Barber Shop API
    info-version: 1.0.0
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:barber_shop}
    password: ${POSTGRES_PASSWORD:barber_shop}
    jdbc:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:barber_shop}
  hibernate-orm:
    schema-management:
      strategy: none
  otel:
    exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
    sdk:
      disabled: ${OTEL_SDK_DISABLED:false}   # true en local, false en producción
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] [traceId=%X{traceId}] (%t) %s%e%n"
    category:
      "org.barbershop": DEBUG
      "org.hibernate.SQL": DEBUG
      "io.quarkus.bootstrap.classloading": WARN